<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="footer">
    <meta name="keywords" content="footer, SwinVN, Project2">
    <meta name="author" content="COS10026.1 Group 6">
</head>
<footer class="site-footer">
    <div class="footer_container">
      <p>TheDataFlow &copy; 2025 — COS10026 Project Part 2</p>
      <p>Contact: <a href="mailto:info@thedataflow.com.au">info@thedataflow.com.au</a></p>
      <p>Our Jira project management link:
        <a
          href="https://kevinlamkhai7.atlassian.net/jira/software/projects/SCRUM/boards/1?atlOrigin=eyJpIjoiMzYxODI3ZDVkZWM4NDI0NDhkY2QwMTFmMzhhNGEzNDYiLCJwIjoiaiJ9" target="_blank">Jira
          Project
        </a></p>
      <p>Our Github repository link: <a href="https://github.com/WebTechnologyProject-Sep2025/projectpart2-cos10026-1-group-6-1" target="_blank">Group 6
          Github repository</a></p>
    </div>
  </footer>