<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="nav">
    <meta name="keywords" content="nav, SwinVN, Project2">
    <meta name="author" content="COS10026.1 Group 6">
</head>
<nav>
      <a href="index.html" class="menu_left">
        <img src="images/logo_dataflow.png" alt="Company Logo">
        <span>DataFlow</span>
      </a>

      <div class="menu_right_group">
        <a href="index.php" class="menu_right">Home</a>
        <a href="jobs.php" class="menu_right">Description</a>
        <a href="apply.php" class="menu_right">Application</a>
        <a href="about.php" class="menu_right">About us</a>
        <a href="enhancements.php" class="menu_right">Enhancements</a>
      </div>
</nav>